xelashop/xelashop/urls.py
from django.contrib import admin
from django.urls import path
from xelashopapp.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('men/', men_product, name='men'),
    path('women/', women_product, name="women"),
    path('men/search/', search, name="search"),
    path('women/search/', search_women, name="search_women"),
    path('men_product_details/<int:product_id>/', men_product_details, name="men_product_details"),
    path('women_product_details/<int:product_id>/', women_product_details, name="women_product_details"),
    path('checkout/', checkout, name='checkout'),
    path('final_site/', final_site, name="final_site"),
    path('item/delete/<int:item_id>/', delete_item, name='delete_item'),
    path('process_order/', process_order, name='process_order'),
    path('add_to_bag/<int:product_id>/', add_to_bag, name='add_to_bag'),
    path('item/delete/<int:item_id>/', delete_item, name='delete_item'),
    path('cart/item/delete/<int:item_id>/', delete_cart_item, name='delete_cart_item'),
    path('order_confirmation/<int:order_id>/', order_confirmation, name='order_confirmation'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xelashop/xelashopapp/models.py
from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female')
    ]
    name = models.CharField(max_length=255)
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE,null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        return self.name


class Image(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')

    def __str__(self):
        return self.product.name


class Product(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female')
    ]
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    color = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    season = models.CharField(max_length=255)
    material = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='product_images')
    quantity = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class MenProduct(Product):
    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        self.gender = 'M'
        super().save(*args, **kwargs)


class WomenProduct(Product):
    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        self.gender = 'F'
        super().save(*args, **kwargs)


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Showing cart for: {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product} ({self.quantity}) have been added"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_number = models.IntegerField(default=int(timezone.now().timestamp()))
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=255)
    payment_method = models.CharField(max_length=100, null=True)
    shipping_method = models.CharField(max_length=255)
    shipping_address = models.TextField(max_length=100, null=True)
    phone = models.CharField(max_length=50)
    products = models.ManyToManyField(Product, related_name='orders')

    def __str__(self):
        return f"Order #{self.pk} by {self.user}"

    def calculate_total_amount(self):
        total = 0
        cart_items = self.cart.items.all()
        for cart_item in cart_items:
            total += cart_item.product.price * cart_item.quantity
        return total

xelashop/xelashopapp/forms.py
from django import forms
from .models import *


class ItemForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'color', 'price', 'quantity', 'photo', 'category', 'material']


class CheckoutForm(forms.ModelForm):
    PAYMENT_CHOICES = [
        ('bank_transfer', 'Bank Transfer'),
        ('paypal', 'Paypal'),
        ('credit_card', 'Credit Card'),
    ]

    payment_method = forms.ChoiceField(choices=PAYMENT_CHOICES, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Order
        fields = ['shipping_address', 'phone', 'shipping_method', 'payment_method']
        labels = {
            'shipping_address': 'Shipping Address',
            'phone': 'Phone Number',
            'shipping_method': 'Shipping Method',
            'payment_method': 'Payment Method',
        }

xelashop/xelashopapp/views.py
from datetime import date

from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import CheckoutForm, ItemForm
from django.contrib.auth.forms import UserCreationForm
from decimal import Decimal
import random


# Create your views here.
def index(request):
    return render(request, "index.html")


def men_product(request):
    query = request.GET.get('search_query', '')
    category = request.GET.get('category')  # Use getlist to get multiple values
    material = request.GET.getlist('material')
    color = request.GET.getlist('color')
    size = request.GET.getlist('size')
    men_products = MenProduct.objects.filter(gender='M')

    if query:
        men_products = men_products.filter(category__name__icontains=query)
    if category:  # Use the plural form for the variable
        men_products = men_products.filter(category__in=category)
    if material:
        men_products = men_products.filter(material__in=material)
    if color:
        men_products = men_products.filter(color__in=color)
    if size:
        men_products = men_products.filter(size__in=size)

    return render(request, 'men.html', {'men_products': men_products, 'query': query, 'selected_categories': category,
                                        'selected_material': material, 'selected_color': color, 'selected_size': size,
                                        'user': request.user})


def women_product(request):
    query = request.GET.get('search_query', '')
    category = request.GET.get('category')
    material = request.GET.getlist('material')
    color = request.GET.getlist('color')
    size = request.GET.getlist('size')
    women_products = WomenProduct.objects.filter(gender='F')

    if query:
        women_products = women_products.filter(category__name__icontains=query)
    if category:
        women_products = women_products.filter(category__in=category)
    if material:
        women_products = women_products.filter(material__in=material)
    if color:
        women_products = women_products.filter(color__in=color)
    if size:
        women_products = women_products.filter(size__in=size)

    return render(request, 'women.html',
                  {'women_products': women_products, 'query': query, 'selected_categories': category,
                   'selected_material': material, 'selected_color': color, 'selected_size': size,
                   'user': request.user})


def search(request):
    search_query = request.GET.get('q')

    search_results = MenProduct.objects.filter(gender='M', name__icontains=search_query)

    return render(request, 'men.html', {'search_results': search_results, 'search_query': search_query})


def search_women(request):
    search_query = request.GET.get('q')

    search_results = WomenProduct.objects.filter(gender='F', name__icontains=search_query)

    return render(request, 'women.html', {'search_results': search_results, 'search_query': search_query})


@login_required(login_url='login')
def men_product_details(request, product_id):
    men_products = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        color = request.POST.get('color')
        size = request.POST.get('size')

        if quantity <= men_products.quantity:
            cart_item, created = CartItem.objects.get_or_create(cart=cart, product=men_products)
            cart_item.quantity = quantity
            cart_item.color = color
            cart_item.size = size
            cart_item.save()
            return redirect('checkout')
        else:
            return HttpResponse("Insufficient quantity available")
    return render(request, 'menproduct.html', {'men_products': men_products})


@login_required(login_url='login')
def women_product_details(request, product_id):
    women_products = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        color = request.POST.get('color')
        size = request.POST.get('size')

        if quantity <= women_products.quantity:
            cart_item, created = CartItem.objects.get_or_create(cart=cart, product=women_products)
            cart_item.quantity = quantity
            cart_item.color = color
            cart_item.size = size
            cart_item.save()
            return redirect('checkout')
        else:
            return HttpResponse("Insufficient quantity available")
    return render(request, 'womenproduct.html', {'women_products': women_products})


@login_required
def delete_item(request, item_id):
    item = get_object_or_404(Product, id=item_id)
    item.delete()
    return redirect('checkout')


@login_required
def edit_item(request, item_id):
    item = get_object_or_404(Product, item_id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('menproduct', product_id=item.id)
        else:
            form = ItemForm(instance=item)
        return render(request, 'edit_product.html', {'form': form, 'item': item})


@login_required(login_url='login')
def add_item(request):
    items = CartItem.objects.filter(cart__user=request.user)
    cart_total = sum(item.product.price * item.quantity for item in items)
    context = {
        'cart_items': items,
        'total': cart_total,
        'colors': set(item.color for item in items),
        'sizes': set(item.size for item in items),
    }
    return render(request, 'checkout.html', context)


@login_required(login_url='login')
def delete_cart_item(request, item_id):
    item = get_object_or_404(CartItem, id=item_id)
    item.delete()
    return redirect('checkout')


@login_required(login_url='login')
def checkout(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.cart = request.user.cart
            order.total_amount = order.calculate_total_amount()
            order.save()

            items = order.cart.items.all()
            for cart_item in items:
                cart_item.product.quantity -= cart_item.quantity
                cart_item.product.save()

            request.user.cart.items.all().delete()

            return redirect('final_site')
    else:
        form = CheckoutForm()

    cart_items = request.user.cart.items.all()
    total_price = sum(item.product.price * item.quantity for item in cart_items)

    context = {'form': form, 'cart_items': cart_items, 'total_price': total_price}
    return render(request, 'checkout.html', context)


@login_required(login_url='login')
def final_site(request):
    return render(request, 'order_confirmation.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            return render(request, 'login.html', {'error': 'Invalid username or password. Please try again.'})
    return render(request, 'login.html')


def generate_random_number():
    order_number = random.randint(100000, 999999)
    while Order.objects.filter(order_number=order_number).exists():
        order_number = random.randint(100000, 999999)
    return order_number


@login_required
def process_order(request):
    if request.method == 'POST':
        total_price = Decimal(request.POST.get('total_price'))
        payment_method = request.POST.get('payment_method')
        shipping_address = request.POST.get('shipping_address')
        product_ids = request.POST.getlist('products')
        products = Product.objects.filter(id__in=product_ids)
        customer = request.user

        order = Order(
            user=customer,
            order_number=generate_random_number(),
            cart=request.user.cart,
            total_amount=total_price,
            created_at=timezone.now(),
            status='Pending',
            payment_method=payment_method,
            shipping_method='Express',
            shipping_address=shipping_address,
        )
        order.save()

        order.products.set(products)

        order.total_amount = order.calculate_total_amount()
        order.save()

        return redirect('order_confirmation', order_id=order.id)

    return render(request, 'checkout.html')


@login_required
def add_to_bag(request, product_id):
    if request.method == 'POST':
        product = Product.objects.get(pk=product_id)
        quantity = int(request.POST.get('quantity'))

        cart, created = Cart.objects.get_or_create(user=request.user)
        cart_item = CartItem.objects.create(cart=cart, product=product, quantity=quantity)

        return redirect('checkout')

    return HttpResponse('Invalid request')


def order_confirmation(request, order_id):

xelashop/xelashopapp/templates/edit_product.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit</title>
</head>
<body>

</body>
</html>

xelashop/xelashopapp/templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fenix&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Felipa&display=swap" rel="stylesheet">
    <title>Log In!</title>
</head>
<body class="container">
<style>
        *, body, html{
            background-color: lightpink;
        }

        h2 {
            color: black;
            font-size: 60px;
        }
        .form-rounded{
            border-radius: 1rem;
        }
    </style>
<h1 class="text-center" style="font-size: 70px;font-family: 'Fenix', serif;font-weight: 500;">Xela</h1>
<div class="mt-5 p-3 d-flex flex-column align-items-center text-center">
    <h2 class="text-center">Log In</h2>
    <div class="card-body">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 d-flex flex-column">
                <label for="username" class="form-label text-start fs-5">Username</label>
                <input type="text" class="form-control form-rounded" id="username" name="username" placeholder="enter your username" style="width: 400px">
            </div>
            <div class="mb-3 d-flex flex-column">
                <label for="password" class="form-label text-start fs-5">Password</label>
                <input type="password" class="form-control form-rounded" id="password" name="password" placeholder="enter your password" style="width: 400px">
            </div>
            <button type="submit" class="btn btn-dark rounded-pill w-50 fs-5">Login</button>
        </form>
        <div class="mt-3 text-center fs-5">
            New here? <a href="{% url 'register' %}">Sign up</a> for an account.
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

xelashop/xelashopapp/templates/menproduct.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fenix&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Felipa&display=swap" rel="stylesheet">
    <title>Men`s Shopping</title>
</head>
<body>
<style>

    h1 {
        font-size: 50px;
    }

    p {
        font-size: 25px;
    }

    html, body {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        background-color: #C6A4A4;
    }

    footer {
        margin-top: auto;
    }

    * {
        scroll-behavior: smooth;
    }

    .img-fluid {
        width: 500px;
        height: 600px;
        border-radius: 5%;
    }

    .navbar-brand {
        font-size: 80px;
        font-family: 'Fenix', serif;
        margin: 0 !important;
        font-weight: 500;
    }

    .navbar-nav .nav-link {
        padding: 10px 30px;
    }

    .navbar-collapse {
        display: flex;
    }

    .navbar svg {
        width: 40px;
        height: 40px;
    }

    .nav-link {
        font-size: 24px;
        padding-left: 70px !important;
        padding-right: 30px !important;
        font-weight: 500;
        min-width: 220px;
    }

    .nav-link.active {
        font-weight: 600;
    }

    .bg-body-tertiary {
        background-color: transparent !important;
    }

    .btn {
        width: 120px;
        height: 40px;
        font-size: 18px;
        text-align: center;
    }

    .slika {
        width: 170px;
        height: 230px;
    }

    .size-selection {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        margin-top: 20px;
    }

    .size-selection label {
        margin-right: 10px;
    }

    .form-check-input, .form-check-label {
        font-size: 20px;
    }

    @media (min-width: 1200px) and (max-width: 1600px) {
        .img-fluid {
            height: 430px;
            width: 90%;
        }

        .slika {
            height: 180px;
            margin: 0;
            padding: 0;
            width: 150px;
        }

        h1 {
            font-size: 36px;
            margin: 0;
            padding: 0;
        }

        p {
            font-size: 20px;
            margin: 0;
            padding: 0;
        }

        .form-check label {
            font-size: 15px;
        }

        .form-check input {
            font-size: 18px;
        }

        .btn {
            margin-bottom: 10px;
        }

        .product {
            margin-top: -30px;
        }

        .price-button-container {
            display: flex;
            flex-direction: column;
            align-items: end;
        }

        .price-button-container p {
            font-weight: bold;
        }
    }
</style>
<header>
    <div class="container ">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid ">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center " id="navbarNavAltMarkup">
                    <div class="navbar-nav justify-content-evenly align-items-center">
                        <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
                        <a class="nav-link " href="{% url  'men' %}">Shop</a>
                        <a class="navbar-brand" href="{% url 'index' %}">Xela</a>
                        <a class="nav-link" href="#">Categories</a>
                        <a class="nav-link" href="#">About</a>
                    </div>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
                    <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                </svg>
            </div>
        </nav>
    </div>
</header>
<div class="container mt-4">
    <div class="row product">
        <div class="col-lg-5">
            <img class="img-fluid" src="{{ MEDIA_URL }}{{ men_products.photo.url }}" alt="Product Image">
        </div>
        <div class="col-lg-5">
            <h1>{{ men_products.name }}</h1>
            <p>Material: <b>{{ men_products.material }}</b></p>
            <p>Season: <b>{{ men_products.season }}</b></p>
            <div class="mt-2">
                {% for image in men_products.image_set.all %}
                    <img class="img-fluid slika" src="{{ MEDIA_URL }}{{ image.image.url }}" alt="Product Image">
                {% endfor %}
            </div>
            {#            <form action="{% url 'men_product_details' men_products.id %}" method="POST">#}
            {#                {% csrf_token %}#}
            <form method="post" action="{% url 'add_to_bag' product_id=men_products.id %}">
                {% csrf_token %}
                <p>Choose quantity</p>
                <input type="hidden" name="product_id" value="{{ men_products.id }}">
                <input type="number" name="quantity" value="1" min="1" style="width: 50px">

                <p class="mt-2">Choose your Color:</p>
                <div class="form-check form-check-inline">
                    <div class="form-check form-check-inline text-left">
                        <input class="form-check-input" type="checkbox" id="color_white" name="color[]" value="White">
                        <label for="color_white" class="form-check-label"><b>White</b></label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="color_black" name="color[]" value="Black"
                               style="background-color: black">
                        <label for="color_black" class="form-check-label"><b>Black</b></label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="color_yellow" name="color[]" value="Yellow"
                               style=" background-color: yellow">
                        <label for="color_yellow" class="form-check-label"><b>Yellow</b></label>
                    </div>
                </div>
                <p class="mt-1">Choose your Size:</p>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="size[]" id="size_XS" value="XS">
                    <label class="form-check-label" for="size_XS"><b>XS</b></label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="size[]" id="size_S" value="S">
                    <label class="form-check-label" for="size_S"><b>S</b></label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="size[]" id="size_M" value="M">
                    <label class="form-check-label" for="size_M"><b>M</b></label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="size[]" id="size_L" value="L">
                    <label class="form-check-label" for="size_L"><b>L</b></label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="size[]" id="size_XL" value="XL">
                    <label class="form-check-label" for="size_XL"><b>XL</b></label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="size[]" id="size_XXL" value="XXL">
                    <label class="form-check-label" for="size_XXL"><b>XXL</b></label>
                </div>
                <div class="price-button-container">
                    <p style="font-size: 25px;" class="align-items-start me-3 total-price">{{ men_products.price }}$</p>
                    <a href="#">
                        <form method="get" action="{% url 'checkout' %}">
                            <input type="hidden" name="size" value="selected_size">
                            <input type="hidden" name="color" value="selected_color">
                            <button type="submit" class="btn btn-dark rounded-pill">Buy Now</button>
                        </form>
                    </a>
                </div>
            </form>
            </form>
        </div>
    </div>
</div>
<script>
    // Get the quantity input field and total price element
    const quantityInput = document.querySelector('input[name="quantity"]');
    const totalPriceElement = document.querySelector('.total-price');

    // Get the initial price and calculate the total
    const initialPrice = parseFloat(totalPriceElement.textContent);
    let total = initialPrice;

    // Function to format the price with two decimal places and a dollar sign
    const formatPrice = (price) => {
        return price.toFixed(2) + '$';
    };

    // Function to update the total price
    const updateTotalPrice = () => {
        const quantity = parseInt(quantityInput.value);
        total = initialPrice * quantity;
        totalPriceElement.textContent = formatPrice(total);
    };

    // Listen for changes in the quantity input field
    quantityInput.addEventListener('change', updateTotalPrice);
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>